version: '4'
services:
  app:
    image: dev-esthetics-image
    ports:
      - "8081:8080"
    environment:
          - SPRING_PROFILES_ACTIVE=production
          - SPRING_DATASOURCE_URL=jdbc:mysql://192.168.1.103:3306/dev_estheticsdb

    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: BetweenUs
      MYSQL_DATABASE: dev_estheticsdb
      MYSQL_USER: esthetics_user
      MYSQL_PASSWORD: esthetics_password
    ports:
      - "3307:3306"
